spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: "root"
    password: ""

  application:
    name: promocode-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

